version: "3.8"

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
