# Prod
spring.jpa.hibernate.ddl-auto=create-drop
#Dev
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptochimp
spring.datasource.username=postgres
spring.datasource.password=james123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.client.registration.google.client-id=559661680902-2sg3m7324o3rc9qlsidqlnsdps5glsar.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=Pe_k-413_HoYKXG8ikYaMxzz