# Prod
spring.jpa.hibernate.ddl-auto=create-drop
#Dev
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptochimp
spring.datasource.username=postgres
spring.datasource.password=james123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true