name: E2E

on: [pull_request, push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: SKIP_ENV_VALIDATION=true npm run build
          start: npm start
